<h2 id="q.-what-is-an-error-first-callback">Q. <strong><em>What is an error-first callback?</em></strong></h2>
<p>The pattern used across all the asynchronous methods in Node.js is called <em>Error-first Callback</em>. Here is an example:</p>
<div class="sourceCode" id="cb1"><pre class="sourceCode javascript"><code class="sourceCode javascript"><a class="sourceLine" id="cb1-1" title="1"><span class="va">fs</span>.<span class="at">readFile</span>(<span class="st">&quot;file.json&quot;</span><span class="op">,</span> <span class="kw">function</span> (err<span class="op">,</span> data) <span class="op">{</span></a>
<a class="sourceLine" id="cb1-2" title="2">  <span class="cf">if</span> (err) <span class="op">{</span></a>
<a class="sourceLine" id="cb1-3" title="3">    <span class="va">console</span>.<span class="at">error</span>(err)</a>
<a class="sourceLine" id="cb1-4" title="4">  <span class="op">}</span></a>
<a class="sourceLine" id="cb1-5" title="5">  <span class="va">console</span>.<span class="at">log</span>(data)</a>
<a class="sourceLine" id="cb1-6" title="6"><span class="op">}</span>)</a></code></pre></div>
<p>Any asynchronous method expects one of the arguments to be a callback. The full callback argument list depends on the caller method, but the first argument is always an error object or null. When we go for the asynchronous method, an exception thrown during function execution cannot be detected in a try/catch statement. The event happens after the JavaScript engine leaves the try block.</p>
<p>In the preceding example, if any exception is thrown during the reading of the file, it lands on the callback function as the first and mandatory parameter.</p>
<div data-align="right">
<pre><code>&lt;b&gt;&lt;a href=&quot;#&quot;&gt;â†¥ back to top&lt;/a&gt;&lt;/b&gt;</code></pre>
</div>
